services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: grafana
    volumes:
      - ./data/postgres:/var/lib/postgresql
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - 6379:6379